version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: npm-deps-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - out

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Create and Deploy to Cloudflare Pages
          command: |
            # Try to create project (will fail if it exists)
            npx wrangler pages project create circleci-books-pages || true
            # Deploy to the project
            npx wrangler pages deploy out --project-name=circleci-books-pages

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
