version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: npm-deps-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - out

  deploy:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm ci
      - run:
          name: Deploy to Cloudflare Pages
          command: npx wrangler pages deploy out --project-name circleci-books-pages --compatibility-date 2024-07-01

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
